version: 0.2

phases:
  install:
    commands:
      - echo Installing NVM...
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
      - . ~/.nvm/nvm.sh
      - nvm install 21.5.0
      - nvm use 21.5.0
      - node --version
      - echo Installing source NPM dependencies...
      - npm install
  pre_build:
    commands:
      - echo Running tests...
      - npm test
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
  discard-paths: yes
