version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 21.5.0
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  pre_build:
    commands:
      - echo Running tests...
      - npm test
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Uploading build to S3 bucket...
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
  discard-paths: yes
